"""Seeded split manifests (val_tune / val_cal / val_test, HIL poolA / poolB) with SHA-256.

The split rule is a pure function of (sorted filenames, fractions, seed, domain key), so the
committed manifests in `splits/` can be regenerated byte-for-byte (`make splits`, tested).

* Names are sorted, then permuted with `default_rng(SeedSequence([seed, key]))`, where `key` is a
  fixed per-domain integer (`DOMAIN_KEYS`). Consecutive blocks of the permutation form the splits.
* Sizes: every split but the last gets `N * fraction` rounded half-down (exact rational arithmetic);
  the last takes the remainder. Synthetic validation 11,994 -> 2,399 / 4,798 / 4,797; lightbox
  6,740 -> 3,370 / 3,370; sunlamp 2,791 -> 1,395 / 1,396 (IMPLEMENTATION_PLAN.md section 1.2).
* Each manifest lists its filenames sorted, one per line, LF, trailing newline. `SHA256SUMS`
  (`sha256sum` format) covers every manifest; `load_split` refuses a file whose hash disagrees.

Data roles (CLAUDE.md invariant 3): `val_tune` is the only subset any fitting may see, `val_cal` is
for calibration only, `val_test` and every `*_poolB` are evaluation only. This module only names
frames; it never reads a label.
"""

from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from fractions import Fraction
from pathlib import Path
from typing import Any

import numpy as np

from poseconf.provenance import POSECONF_ROOT, parse_sha256sums, sha256_file

__all__ = [
    "DEFAULT_MANIFEST_DIR",
    "DOMAIN_KEYS",
    "HIL_DOMAINS",
    "MANIFEST_NAMES",
    "SUMS_FILENAME",
    "assign_splits",
    "domain_fractions",
    "load_split",
    "manifest_sha256",
    "manifest_text",
    "split_sizes",
    "write_manifests",
]

#: Fixed per-domain stream keys for the permutation. Never renumber: it would re-split.
DOMAIN_KEYS: dict[str, int] = {"synthetic": 0, "lightbox": 1, "sunlamp": 2}

#: Hardware-in-the-loop domains (poolA / poolB).
HIL_DOMAINS = ("lightbox", "sunlamp")

#: Config key -> manifest suffix, in split order.
_SYNTHETIC_SPLITS = (("val_tune", "val_tune"), ("val_cal", "val_cal"), ("val_test", "val_test"))
_HIL_SPLITS = (("pool_a", "poolA"), ("pool_b", "poolB"))

#: Every committed manifest, by name (`splits/<name>.txt`).
MANIFEST_NAMES: tuple[str, ...] = tuple(f"synthetic_{s}" for _, s in _SYNTHETIC_SPLITS) + tuple(
    f"{d}_{s}" for d in HIL_DOMAINS for _, s in _HIL_SPLITS
)

#: Manifest checksum file inside the manifest directory.
SUMS_FILENAME = "SHA256SUMS"

#: Default manifest directory.
DEFAULT_MANIFEST_DIR = POSECONF_ROOT / "splits"

#: Fractions are read as exact rationals with at most this denominator.
_FRACTION_MAX_DENOMINATOR = 10**6


def _rational(fraction: float) -> Fraction:
    return Fraction(fraction).limit_denominator(_FRACTION_MAX_DENOMINATOR)


def split_sizes(n: int, fractions: Sequence[float]) -> list[int]:
    """Split sizes: round-half-down of `n * f` for all but the last, which takes the remainder.

    Args:
        n: Number of frames.
        fractions: Split fractions, each in (0, 1], summing to exactly 1 as rationals.

    Returns:
        Sizes summing to `n`.

    Raises:
        ValueError: On an empty or non-positive fraction list, or fractions not summing to 1.
    """
    if n < 0:
        raise ValueError(f"n must be >= 0, got {n}")
    exact = [_rational(f) for f in fractions]
    if not exact or any(f <= 0 for f in exact):
        raise ValueError(f"fractions must be non-empty and positive, got {list(fractions)}")
    if sum(exact) != 1:
        raise ValueError(f"fractions must sum to exactly 1, got {list(fractions)} = {sum(exact)}")
    sizes = [math.ceil(n * f - Fraction(1, 2)) for f in exact[:-1]]
    sizes.append(n - sum(sizes))
    if sizes[-1] < 0:
        raise ValueError(f"split sizes {sizes} for n={n} are not all non-negative")
    return sizes


def assign_splits(
    names: Sequence[str], fractions: Mapping[str, float], *, seed: int, key: int
) -> dict[str, list[str]]:
    """Assign filenames to splits deterministically.

    Args:
        names: Filenames, unique; order does not matter (they are sorted first).
        fractions: Split name -> fraction, in split order (the last takes the remainder).
        seed: The splits seed (`configs/conformal.yaml` `splits.seed`).
        key: The domain's stream key (`DOMAIN_KEYS`).

    Returns:
        Split name -> sorted filenames.

    Raises:
        ValueError: On duplicate names or invalid fractions.
    """
    ordered = sorted(names)
    if len(set(ordered)) != len(ordered):
        raise ValueError("filenames must be unique")
    sizes = split_sizes(len(ordered), list(fractions.values()))
    perm = np.random.default_rng(np.random.SeedSequence([seed, key])).permutation(len(ordered))
    out: dict[str, list[str]] = {}
    start = 0
    for split, size in zip(fractions, sizes, strict=True):
        out[split] = sorted(ordered[i] for i in perm[start : start + size])
        start += size
    return out


def domain_fractions(config: Mapping[str, Any]) -> dict[str, dict[str, float]]:
    """Per-domain manifest name -> fraction, from `configs/conformal.yaml`'s `splits` block.

    Args:
        config: The loaded conformal config.

    Returns:
        `{"synthetic": {"synthetic_val_tune": 0.2, ...}, "lightbox": {...}, "sunlamp": {...}}`.
    """
    block = config["splits"]
    synthetic = block["synthetic_validation"]
    hil = block["hil"]
    out = {"synthetic": {f"synthetic_{s}": float(synthetic[k]) for k, s in _SYNTHETIC_SPLITS}}
    for domain in HIL_DOMAINS:
        out[domain] = {f"{domain}_{s}": float(hil[k]) for k, s in _HIL_SPLITS}
    return out


def manifest_text(names: Sequence[str]) -> str:
    """Canonical manifest contents: sorted names, one per line, LF, trailing newline."""
    ordered = sorted(names)
    if any(not name or "\n" in name or name != name.strip() for name in ordered):
        raise ValueError("filenames must be non-empty with no whitespace padding or newlines")
    return "".join(f"{name}\n" for name in ordered)


def write_manifests(splits: Mapping[str, Sequence[str]], out_dir: str | Path) -> Path:
    """Write `<out_dir>/<name>.txt` for each split plus `SHA256SUMS`.

    Args:
        splits: Manifest name -> filenames. Must be exactly `MANIFEST_NAMES`.
        out_dir: Destination directory (created).

    Returns:
        The `SHA256SUMS` path.

    Raises:
        ValueError: If the split names are not exactly `MANIFEST_NAMES`.
    """
    if set(splits) != set(MANIFEST_NAMES):
        raise ValueError(f"expected manifests {sorted(MANIFEST_NAMES)}, got {sorted(splits)}")
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    lines = []
    for name in sorted(splits):
        path = out / f"{name}.txt"
        path.write_bytes(manifest_text(splits[name]).encode("utf-8"))
        lines.append(f"{sha256_file(path)}  {path.name}\n")
    sums = out / SUMS_FILENAME
    sums.write_bytes("".join(lines).encode("utf-8"))
    return sums


def load_split(name: str, manifest_dir: str | Path = DEFAULT_MANIFEST_DIR) -> list[str]:
    """Read one committed manifest after checking its SHA-256 against `SHA256SUMS`.

    Args:
        name: Manifest name, e.g. `"synthetic_val_cal"`.
        manifest_dir: Directory holding the manifests.

    Returns:
        The filenames, sorted.

    Raises:
        KeyError: If `name` is not a known manifest or is missing from `SHA256SUMS`.
        FileNotFoundError: If the manifest or `SHA256SUMS` is missing.
        ValueError: If the hash disagrees or the file is not in canonical form.
    """
    if name not in MANIFEST_NAMES:
        raise KeyError(f"unknown split manifest {name!r}; expected one of {MANIFEST_NAMES}")
    directory = Path(manifest_dir)
    sums = parse_sha256sums((directory / SUMS_FILENAME).read_text(encoding="utf-8"))
    filename = f"{name}.txt"
    if filename not in sums:
        raise KeyError(f"{directory / SUMS_FILENAME} has no entry for {filename}")
    path = directory / filename
    digest = sha256_file(path)
    if digest != sums[filename]:
        raise ValueError(
            f"{path} SHA-256 {digest} != SHA256SUMS {sums[filename]}; manifests are never edited"
        )
    text = path.read_text(encoding="utf-8")
    names = text.splitlines()
    if manifest_text(names) != text:
        raise ValueError(f"{path} is not in canonical manifest form")
    return names


def manifest_sha256(manifest_dir: str | Path = DEFAULT_MANIFEST_DIR) -> str:
    """SHA-256 of `SHA256SUMS`: one hash that pins every manifest, for result provenance."""
    return sha256_file(Path(manifest_dir) / SUMS_FILENAME)
